site_name: 老赵杂记
site_url: https://archtaurus.github.io/blog
nav:
  - 首页: index.md
  - MkDocs: mkdocs.md
extra_javascript:
  - js/external_links.js # 自动为所有外链添加 target="_blank"
theme:
  language: zh
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    scheme: dark
    primary: indigo
  features:
    - content.code.copy # 显示复制按钮
extra:
  generator: false
