site_author: 老赵
site_name: 老赵杂记
site_url: https://io-oi.cc/blog/
site_description: "老赵杂记"
repo_name: archtaurus/blog
repo_url: https://github.com/archtaurus/blog
nav:
  - 首页: index.md
  - 帮助: help.md
extra_css:
  - stylesheets/custom.css # 自定义样式表
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/external_links.js # 自动为所有外链添加 target="_blank"
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false # 隐藏生成软件声明
theme:
  language: zh # 主题样式名称
  name: material # 主题样式名称 [material mkdocs]
  # custom_dir: theme
  icon:
    repo: fontawesome/brands/github-alt
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.top # 显示返回顶部按钮
    - content.code.copy # 显示复制按钮
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      line_spans: __line
      linenums: true
      anchor_linenums: true
      pygments_lang_class: true
      use_pygments: true # 使用 Pygments 作为高亮引擎
      auto_title: true
