site_author: 老赵
site_name: 老赵杂记
site_url: https://io-oi.cc/blog/
site_description: "老赵杂记"
repo_name: archtaurus/blog
repo_url: https://github.com/archtaurus/blog
nav:
  - 首页: index.md
  - MkDocs: mkdocs.md
extra_css:
  - stylesheets/custom.css # 自定义样式表
extra_javascript:
  - javascripts/external_links.js # 自动为所有外链添加 target="_blank"
extra:
  generator: false # 隐藏生成软件声明
theme:
  language: zh # 主题样式名称
  name: material # 主题样式名称 [material mkdocs]
  custom_dir: theme
  icon:
    repo: fontawesome/brands/github-alt
    # logo: material/glasses
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - content.code.copy # 显示复制按钮
    - content.code.annotate
    - navigation.top
