# ========================
# 基础信息配置
# ========================
site_author: 老赵
site_name: 老赵杂记
site_url: https://io-oi.cc/blog/ # 注意：确保结尾有斜杠
site_description: "老赵杂记"
copyright: |
  ❤ 1975~2025 <a href="https://github.com/archtaurus" target="_blank" rel="noopener">Zhao Xin</a>

# ========================
# 仓库信息
# ========================
repo_name: archtaurus/blog # 显示在右上角的仓库名称
repo_url: https://github.com/archtaurus/blog # 仓库链接

# ========================
# 导航菜单
# ========================
nav:
  - 首页: index.md
  - 数学: math.md
  - 编程: code.md
  - 帮助: help.md
  - 收藏: links.md
  - 留言: comments.md

# ========================
# 资源文件配置
# ========================
extra_css:
  - stylesheets/custom.css # 自定义CSS文件路径

extra_javascript:
  # CDN1
  # - https://cdn.jsdelivr.net/npm/js-polyfills@0.1.43/polyfill.min.js?features=es6 # ES6兼容垫片（可选）
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # MathJax 3
  # 国内备用CDN（注释状态）:
  # - https://cdn.bootcdn.net/ajax/libs/core-js/3.40.0/minified.min.js
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
  - javascripts/external_links.js # 自动为外链添加 target="_blank"
  - javascripts/core-js.3.41.minified.js # ES6兼容垫片（可选）
  - javascripts/mathjax/tex-chtml-full.js # MathJax 3

extra:
  generator: false # 隐藏"Powered by MkDocs"声明
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/archtaurus # 社交图标链接

# ========================
# 主题配置
# ========================
theme:
  language: zh # 中文界面
  name: material # 使用Material主题
  custom_dir: theme
  font:
    text: Noto Serif SC # 正文字体
    code: JetBrains Mono # 代码字体
  icon:
    repo: fontawesome/brands/github-alt # 仓库图标
  logo: images/logo.png # 网站Logo路径
  favicon: images/favicon.png # 网站Icon路径
  # 主题功能开关
  features:
    - content.code.annotate # 代码注释增强
    - content.code.copy # 代码复制按钮
    - content.tabs.link # 标签页可链接
    # - navigation.tabs # 顶部标签导航
    # - navigation.top # 返回顶部按钮
    - search.highlight # 搜索高亮
    - search.suggest # 搜索建议
    # - toc.integrate # 集成目录
  # 颜色方案配置
  palette:
    - scheme: default # 浅色模式
      primary: grey # 主色调
      toggle:
        icon: material/lightbulb-outline # 切换图标
        name: 切换到深色模式 # 切换提示文字
    - scheme: slate # 深色模式
      primary: black # 主色调
      toggle:
        icon: material/lightbulb # 切换图标
        name: 切换到浅色模式 # 切换提示文字

# ========================
# 插件配置
# ========================
plugins:
  - search: # 搜索插件
      lang:
        - en
        - ja
        - zh # 中文分词
      separator: '[\s\u200b\-\.\_\#]+' # 增加对#号的识别
# ========================
# Markdown 扩展
# ========================
markdown_extensions:
  # 基础扩展
  - attr_list # 属性列表支持，为元素指定属性、类名、样式
  - pymdownx.emoji # Emoji支持
  - pymdownx.snippets # 代码片段
  - pymdownx.arithmatex: # 数学公式支持
      generic: true # 允许通用 LaTeX 语法
  # 内容增强
  - admonition # 警告框
  - footnotes # 脚注
  - pymdownx.details # 折叠内容
  - pymdownx.superfences # 高级代码块
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.mark # 标记文本
  # 代码高亮配置
  - pymdownx.highlight:
      use_pygments: true # 使用 Pygments 作为高亮引擎
      auto_title: true # 自动标题
      linenums: true # 行号支持
      line_spans: __line # 行跨度
      anchor_linenums: true # 行号锚点
      pygments_lang_class: true # 语言类
